name: Setup Environment
description: "Sets up mise and installs tools"

runs:
  using: "composite"
  steps:
    - name: Set up mise
      uses: jdx/mise-action@v2

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8.15.4

    - name: Run bootstrap script
      run: bash ./bootstrap.sh
      shell: bash
      working-directory: ${{ github.workspace }}
