name: CI for Ktt-backend
on:
  push:
    paths:
      - 'KTT-backend/**'

jobs:
  ktt-backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: KTT-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Lint Project
        uses: ./.github/actions/lint
        with:
          project-dir: KTT-backend
        continue-on-error: true

      - name: Cache Maven
        uses: ./.github/actions/cache-maven
        with:
          project-dir: ./KTT-backend

      - name: Build Project
        uses: ./.github/actions/build
        with:
          project-dir: KTT-backend
