name: CI for KTT-frontend
on:
  push:
    paths:
      - 'KTT-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: KTT-frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Project
        uses: ./.github/actions/build
        with:
          project-dir: KTT-frontend
