name: Release and Publish Packages

on:
  push:
    branches:
      - '**'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Get current branch
        id: vars
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
      - name: Publish on PR/dev branch
        if: steps.vars.outputs.branch != 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing from feature/PR branch..."
          pnpm changeset publish
      - name: Version packages on main
        if: steps.vars.outputs.branch == 'main'
        run: pnpm changeset version

      - name: Commit version bump
        if: steps.vars.outputs.branch == 'main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump via Changesets" || echo "Nothing to commit"
          git push origin main
      - name: Publish to npm
        if: steps.vars.outputs.branch == 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm changeset publish
