name: Release Workflow (No Corepack)

on:
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm' # We'll install pnpm via npm now

      - name: Install pnpm manually (skip corepack)
        run: |
          npm install -g pnpm@8.15.4
          pnpm -v

      - name: Install dependencies
        run: pnpm install

      - name: Get current branch
        id: vars
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Publish on PR or develop
        if: steps.vars.outputs.branch != 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm changeset publish

      - name: Version packages
        if: steps.vars.outputs.branch == 'main'
        run: pnpm changeset version

      - name: Commit changelog + versions
        if: steps.vars.outputs.branch == 'main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump via Changesets" || echo "No changes"
          git push origin main

      - name: Publish to npm
        if: steps.vars.outputs.branch == 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm changeset publish
