name: Release

on:
  push:
    branches:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and enable corepack
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable corepack & activate pnpm manually
        run: |
          corepack enable
          corepack prepare pnpm@8.15.4 --activate
          pnpm -v  # Confirm pnpm works
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: Get current branch
        id: vars
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Publish from PR/dev branch
        if: steps.vars.outputs.branch != 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm changeset publish

      - name: Version packages
        if: steps.vars.outputs.branch == 'main'
        run: pnpm changeset version

      - name: Commit and push version bump
        if: steps.vars.outputs.branch == 'main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump via changesets" || echo "No changes"
          git push origin main

      - name: Publish to npm
        if: steps.vars.outputs.branch == 'main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm changeset publish
